% Script to programatically generate 10 dipoles changing:
% - simulated signal, and 
% - dipole location
%
% Raymundo Cassani, 2022

% Input files
sFiles = [];
SubjectNames = {...
    'Subject01'};

% Start a new report
bst_report('Start', sFiles);

for iTrial = 1 : 10
    % Process: Simulate generic signals
    sFile = bst_process('CallProcess', 'process_simulate_matrix', [], [], ...
        'subjectname', SubjectNames{1}, ...
        'condition',   'NewCondition', ...
        'samples',     1000, ...
        'srate',       1000, ...
        'matlab',      ['Data(1,:) = ', num2str(iTrial), '*sin(2*pi*t);']);

    % Process: Set name: Simulated bilateral
    sFile = bst_process('CallProcess', 'process_set_comment', sFile, [], ...
        'tag',           'Simulated bilateral', ...
        'isindex',       1);

    % Process: Simulate recordings from dipoles
    sFile = bst_process('CallProcess', 'process_simulate_dipoles', sFile, [], ...
        'dipoles',  ['-48, ', num2str(iTrial), ', -4, 1, 0, -1'], ...
        'cs',       'mni', ...  % MNI
        'meg',      'os_meg', ...  % Overlapping spheres
        'openmeeg', struct(...
             'BemFiles',     {{}}, ...
             'BemNames',     {{'Scalp', 'Skull', 'Brain'}}, ...
             'BemCond',      [1, 0.0125, 1], ...
             'BemSelect',    [1, 1, 1], ...
             'isAdjoint',    0, ...
             'isAdaptative', 1, ...
             'isSplit',      0, ...
             'SplitLength',  4000), ...
        'duneuro',  struct(...
             'FemCond',             [], ...
             'FemSelect',           [], ...
             'UseTensor',           0, ...
             'Isotropic',           1, ...
             'SrcShrink',           0, ...
             'SrcForceInGM',        0, ...
             'FemType',             'fitted', ...
             'SolverType',          'cg', ...
             'GeometryAdapted',     0, ...
             'Tolerance',           1e-08, ...
             'ElecType',            'normal', ...
             'MegIntorderadd',      0, ...
             'MegType',             'physical', ...
             'SolvSolverType',      'cg', ...
             'SolvPrecond',         'amg', ...
             'SolvSmootherType',    'ssor', ...
             'SolvIntorderadd',     0, ...
             'DgSmootherType',      'ssor', ...
             'DgScheme',            'sipg', ...
             'DgPenalty',           20, ...
             'DgEdgeNormType',      'houston', ...
             'DgWeights',           1, ...
             'DgReduction',         1, ...
             'SolPostProcess',      1, ...
             'SolSubstractMean',    0, ...
             'SolSolverReduction',  1e-10, ...
             'SrcModel',            'venant', ...
             'SrcIntorderadd',      0, ...
             'SrcIntorderadd_lb',   2, ...
             'SrcNbMoments',        3, ...
             'SrcRefLen',           20, ...
             'SrcWeightExp',        1, ...
             'SrcRelaxFactor',      6, ...
             'SrcMixedMoments',     1, ...
             'SrcRestrict',         1, ...
             'SrcInit',             'closest_vertex', ...
             'BstSaveTransfer',     0, ...
             'BstEegTransferFile',  'eeg_transfer.dat', ...
             'BstMegTransferFile',  'meg_transfer.dat', ...
             'BstEegLfFile',        'eeg_lf.dat', ...
             'BstMegLfFile',        'meg_lf.dat', ...
             'UseIntegrationPoint', 1, ...
             'EnableCacheMemory',   0, ...
             'MegPerBlockOfSensor', 0), ...
        'isnoise',  1, ...
        'noise1',   0.1, ...
        'noise2',   0.5, ...
        'savedip',  1, ...
        'savedata', 1);
end

% Save and display report
ReportFile = bst_report('Save');
bst_report('Open', ReportFile);


